### ISSUE TITLE
new request form doesn't submit

### ISSUE THREAD

**Issue by Anupam-dagar** [opencodeiiita/outpassfinal#23]
## Expected Behavior

Form should get submitted.

## Current Behavior

What is the current behavior?

Currently no new request of the form can be created on the portal as there is an error "End time cannot be before present time".

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a new request
2. enter valid data
3. submit the form

## Context

the error can possibly be resolved by fixing validation of field in `forms.py`.

**Comment by CleverFool77** [comment]
@opencodebot claim
