### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by Tlazypanda** [opencodeiiita/outpassfinal#4]
Currently each issue that is opened doesn't follow any template.Kindly create one in root of the directory.You can refer the following links for further help.
https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/
https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by BinduVerma123** [comment]
@opencodebot claim

**Comment by sharmamansi** [comment]
Claim

**Comment by Tlazypanda** [comment]
@sharmamansi Kindly try to claim the issue with proper syntax for the bot

**Comment by Jahanvi21** [comment]
@opencodebot claim

**Comment by Jahanvi21** [comment]
@opencodebot claim

**Comment by CleverFool77** [comment]
@opencodebot claim

**Comment by CleverFool77** [comment]
@opencodebot claim
