### ISSUE TITLE
Create a PR template

### ISSUE THREAD

**Issue by Tlazypanda** [opencodeiiita/outpassfinal#5]
Currently there is no set PR template to be followed in the PR.Inorder to encourage opensource practices create one in the root of the directory.You may visit the following links for further assistance.

https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by littleprodigy** [comment]
@opencodebot claim

**Comment by littleprodigy** [comment]
I have to create a new file in the repository with .root name.

**Comment by littleprodigy** [comment]
@opencodebot unclaim

**Comment by Archies11** [comment]
@opencodebot claim
