### ISSUE TITLE
Improve UI design for Navbar

### ISSUE THREAD

**Issue by Tlazypanda** [opencodeiiita/outpassfinal#6]
Currently the navbar looks completely plain.Improve the design for the navbar. ~~This issue is open for all~~Come up with some exciting new designs.The best submission will be merged.

**Comment by ShipraGaur** [comment]
@opencodebot claim

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by CleverFool77** [comment]
@opencodebot claim.
